In [129]:
#POST-COVID-19 HAZARD DETECTION USING MODERN SENSORS & ML

In [130]:
from pandas import DataFrame 
from random import randint
import random
lst_tmp = []
lst_oxy = []
lst_hrt = [] 
 

for i in range(0, 1000): 
    
    tmp = randint(96,105)
    oxy = randint(85,99)
    hrt = randint(60,130)
   
  
    lst_tmp.append(tmp)
    lst_oxy.append(oxy)
    lst_hrt.append(hrt) 
    
random.shuffle(lst_tmp)
random.shuffle(lst_oxy)
random.shuffle(lst_hrt)      

In [131]:
 import numpy

x = lst_tmp
y = lst_oxy
z = lst_hrt
A = numpy.array((x, y, z), dtype=float)
A

array([[102.,  99., 100., ...,  99.,  96.,  99.],
       [ 89.,  95.,  99., ...,  88.,  89.,  94.],
       [ 81.,  69., 101., ...,  75., 108.,  83.]])

In [132]:
AT= A.T
print(AT)

[[102.  89.  81.]
 [ 99.  95.  69.]
 [100.  99. 101.]
 ...
 [ 99.  88.  75.]
 [ 96.  89. 108.]
 [ 99.  94.  83.]]


In [133]:
df = DataFrame (AT,columns = ['temp','oxygen','heart beat'])
df

temp  oxygen  heart beat
0    102.0    89.0        81.0
1     99.0    95.0        69.0
2    100.0    99.0       101.0
3    102.0    98.0        70.0
4     98.0    89.0       108.0
..     ...     ...         ...
995   96.0    97.0       111.0
996  105.0    91.0        99.0
997   99.0    88.0        75.0
998   96.0    89.0       108.0
999   99.0    94.0        83.0

[1000 rows x 3 columns]

In [134]:
i=0
j=0
k=0
counter=0 
output=[]
while counter < 1000:
  if lst_tmp[i]>int(99):
    if lst_oxy[j]<int(90):
      output.append("possible heart risk")  
      #break
    else:
      if lst_hrt[k]>int(90):
        output.append("no possible risk")  
        #break
      else:
        output.append("no possible risk")  
        #break
  else:
    if lst_oxy[j]<int(90):
      if lst_hrt[k]>int(90):
        output.append("possible risk")  
        #break
      else:
        output.append("mild symptoms to heart risk") 
        #break
    else:
      if lst_hrt[k]>int(90):
        output.append("no possible risk")
        #break
      else:
        output.append("no possible risk") 
        #break 
  i+=1
  j+=1
  k+=1 
  counter+=1

In [135]:
print(output)

['possible heart risk', 'no possible risk', 'no possible risk', 'no possible risk', 'possible risk', 'no possible risk', 'no possible risk', 'no possible risk', 'possible heart risk', 'no possible risk', 'no possible risk', 'no possible risk', 'possible heart risk', 'no possible risk', 'no possible risk', 'no possible risk', 'no possible risk', 'no possible risk', 'no possible risk', 'no possible risk', 'no possible risk', 'no possible risk', 'no possible risk', 'no possible risk', 'no possible risk', 'possible risk', 'no possible risk', 'no possible risk', 'no possible risk', 'possible heart risk', 'possible heart risk', 'possible heart risk', 'no possible risk', 'no possible risk', 'possible heart risk', 'possible risk', 'no possible risk', 'possible risk', 'possible heart risk', 'possible heart risk', 'possible risk', 'possible risk', 'possible heart risk', 'no possible risk', 'no possible risk', 'no possible risk', 'no possible risk', 'no possible risk', 'no possible risk', 'no pos

In [136]:
df1 = DataFrame (output,columns = ['prediction'])
df1

prediction
0            possible heart risk
1               no possible risk
2               no possible risk
3               no possible risk
4                  possible risk
..                           ...
995             no possible risk
996             no possible risk
997  mild symptoms to heart risk
998                possible risk
999             no possible risk

[1000 rows x 1 columns]

In [137]:
import pandas as pd
result = pd.concat([df, df1], axis=1)
result

temp  oxygen  heart beat                   prediction
0    102.0    89.0        81.0          possible heart risk
1     99.0    95.0        69.0             no possible risk
2    100.0    99.0       101.0             no possible risk
3    102.0    98.0        70.0             no possible risk
4     98.0    89.0       108.0                possible risk
..     ...     ...         ...                          ...
995   96.0    97.0       111.0             no possible risk
996  105.0    91.0        99.0             no possible risk
997   99.0    88.0        75.0  mild symptoms to heart risk
998   96.0    89.0       108.0                possible risk
999   99.0    94.0        83.0             no possible risk

[1000 rows x 4 columns]

In [138]:
result.to_csv("result1.csv")


#MACHINE LEARNING MODEL 

In [139]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

In [140]:
df=pd.read_csv("result1.csv") 

In [141]:
y=df["prediction"]

In [142]:
X=df.drop("prediction",axis=1)

In [143]:
X=X.drop("Unnamed: 0",axis=1)

In [144]:
X.head()

temp  oxygen  heart beat
0  102.0    89.0        81.0
1   99.0    95.0        69.0
2  100.0    99.0       101.0
3  102.0    98.0        70.0
4   98.0    89.0       108.0

In [145]:
from sklearn.model_selection import train_test_split

In [146]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42,stratify=y)

In [147]:
from sklearn.preprocessing import MinMaxScaler

In [148]:
scaler=MinMaxScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

#KNN


In [149]:
from sklearn.neighbors import KNeighborsClassifier

In [150]:
model=KNeighborsClassifier(n_neighbors=2)

In [151]:
model.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=2)

In [152]:
model.score(X_test,y_test)

0.9433333333333334

#KNN prediction

In [153]:
C = 34

In [154]:
temp = 9/5 + (C + 32)

In [155]:
data=pd.DataFrame({0:[92],1:[95],2:[temp]})
data=scaler.transform(data)
model.predict(data)

array(['no possible risk'], dtype=object)